### PR TITLE
Prune outdated

### PR DESCRIPTION
**Pull request by hermanbanken**
# Problem
Currently mc-robot fails to delete outdated clusters from ServiceSync status if there are no PubSub events being emitted. If no other clusters exist, there is no reason those events would be send. Therefore, any last remaining cluster will forever keep the history of the previous clusters and might attempt to use those clusters.

# Solution
1. Publish the broadcast not once, but with a certain interval.
2. Prune remote clusters when receiving broadcasts

If we know that we can receive broadcasts from PubSub then we know that the PubSub system is working so we can be sure to remove any stale information (that should already have been updated using that PubSub system if the cluster would still be there).

### CODE REVIEW

**Comment by hermanbanken** [comment]
Ping @klmz

**Comment by hermanbanken** [comment]
Ping @EDeijl

**Comment by EDeijl** [comment]
maar 3 maanden later, maar is dit nog relevant? 😅

**Comment by hermanbanken** [comment]
Ja! Dit is denk ik nog steeds nuttig. Voornamelijk bij het weghalen van clusters, of short lived dev clusters. Het was functionaliteit die ik altijd al bedacht had, maar pas in augustus gemaakt had.

**Pull request merged**
